import "./globals.css";

import { Khand, Open_Sans, Poppins, Inter } from "next/font/google";

const khand = Khand({ subsets: ["latin"], weight: ["400", "500", "700"] });
const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "600"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["600", "700"] });
const inter = Inter({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Car Polish - Home</title>
      </head>
      <body
        className={`${openSans.className} ${khand.className} ${inter.className} ${poppins.variable} bg-main-default`}
      >
        {children}
      </body>
    </html>
  );
}
